### ISSUE TITLE
[BUG] Use HID to connect to ledger on chrome

### ISSUE THREAD

**Issue by imanust** [terra-money/terra-web-extensions#6]
I am on linux and cannot connect to ledger x using this extension (or current terra station extension). Every other extension works (such as metamask). Terra station web app works fine too. Metamask uses HID to connect o ledger via chrome. Please use this method too! Thanks

**Comment by iamssen** [comment]
@imanust I'll check and solve this problem. However, it will take time due to other major updates for the time being. 

Reports on the environment I haven't checked are very valuable. Thank you for the issue.
